matrix:
    - aspell:
          default_encoding: utf-8
          dictionary:
          encoding: utf-8
          exclude:
              - "libs/**"
              - "node_modules/**"
              - "**/libs/**"
              - "**/node_modules/**"
              - "**/changelog.md"
              - "**/CHANGELOG.md"
              - "**/copilot-instructions.md"
          lang: en
          pipeline:
              - markdown_extensions:
                    - pymdownx.superfences
                pyspelling.filters.markdown:
              - comments: false
                ignores:
                    - code
                    - pre
                pyspelling.filters.html:
          sources:
              - "**/*.md"
          wordlists:
              - .wordlist.txt
      name: Markdown
