DISABLE_LINTERS: []
EXCLUDED_DIRECTORIES: [libs, tests, screenshots, node_modules, icons, docs, dist-electron]
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true
FILEIO_REPORTER: true
GITHUB_COMMENT_REPORTER: true
JSON_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true
SARIF_REPORTER: true
TAP_REPORTER: true
DISABLE_ERRORS: true
JAVASCRIPT_DEFAULT_STYLE: prettier
ACTION_ACTIONLINT_CONFIG_FILE: ActionLintConfig.yaml
COPYPASTE_JSCPD_CONFIG_FILE: .jscpd.json
HTML_HTMLHINT_CONFIG_FILE: .htmlhintrc
JAVASCRIPT_PRETTIER_CONFIG_FILE: .prettierrc
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .markdown-link-check.json
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: "^.*(CHANGELOG|README|SECURITY)\\.md$"
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yml
REPOSITORY_KICS_CONFIG_FILE: kics.yaml
SPELL_LYCHEE_CONFIG_FILE: lychee.toml
JSON_PRETTIER_CONFIG_FILE: .prettierrc.json
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml
CSS_STYLELINT_CONFIG_FILE: stylelint.config.js
REPOSITORY_DEVSKIM_CONFIG_FILE: .devskim.json
