---
ACTION_ACTIONLINT_CONFIG_FILE: ActionLintConfig.yaml
CONFIG_REPORTER: true
COPYPASTE_JSCPD_CONFIG_FILE: .jscpd.json
CSS_STYLELINT_CONFIG_FILE: stylelint.config.js
DISABLE_ERRORS: true
DISABLE_LINTERS:
    - CSS_STYLELINT
    - TYPESCRIPT_STANDARD
EXCLUDED_DIRECTORIES: [libs, tests, screenshots, node_modules, icons, docs, dist-electron]
FILEIO_REPORTER: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
HTML_HTMLHINT_CONFIG_FILE: .htmlhintrc
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_CONFIG_FILE: .prettierrc
JSON_PRETTIER_CONFIG_FILE: .prettierrc
JSON_PRETTIER_DISABLE_ERRORS: true
JSON_REPORTER: true
JSON_V8R_DISABLE_ERRORS_IF_LESS_THAN: 2
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .markdown-link-check.json
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: ^.*(CHANGELOG|README|SECURITY)\.md$
MARKDOWN_SUMMARY_REPORTER: true
PLUGINS:
    - https://raw.githubusercontent.com/wesley-dean/mega-linter-plugin-repolinter/refs/heads/main/mega-linter-plugin-repolinter/repolinter.megalinter-descriptor.yml
    - https://raw.githubusercontent.com/andreoliwa/nitpick/v0.35.0/mega-linter-plugin-nitpick/nitpick.megalinter-descriptor.yml
    - https://raw.githubusercontent.com/ssc-services/mega-linter-plugin-salt/main/mega-linter-plugin-salt/salt.megalinter-descriptor.yml
REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yml
REPOSITORY_DEVSKIM_CONFIG_FILE: .devskim.json
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
REPOSITORY_GRYPE_CONFIG_FILE: .grype.yaml
REPOSITORY_KICS_CONFIG_FILE: kics.yaml
SARIF_REPORTER: true
SHOW_ELAPSED_TIME: true
SPELL_CSPELL_CONFIG_FILE: .cspell.json
SPELL_LYCHEE_CONFIG_FILE: lychee.toml
TAP_REPORTER: true
TEXT_REPORTER: true
TYPESCRIPT_STANDARD_DISABLE_ERRORS: true
UPDATED_SOURCES_REPORTER: true
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml
