---
# Schema: https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# Performance optimizations
PARALLEL: true
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: true
PRINT_ALPACA: true
PRINT_ALL_FILES: false
VALIDATE_ALL_CODEBASE: true

# Core configuration
DISABLE_ERRORS: true
FORMATTERS_DISABLE_ERRORS: true
IGNORE_GITIGNORED_FILES: true
IGNORE_GENERATED_FILES: true
FAIL_IF_UPDATED_SOURCES: false
LOG_FILE: .mega-linter.log
LOG_LEVEL: WARNING
SHOW_SKIPPED_LINTERS: true

# Linters configuration
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_DEFAULT_STYLE: markdownlint
TYPESCRIPT_DEFAULT_STYLE: prettier

# Config file references
ACTION_ACTIONLINT_CONFIG_FILE: ActionLintConfig.yaml
COPYPASTE_JSCPD_CONFIG_FILE: .jscpd.json
CSS_STYLELINT_CONFIG_FILE: stylelint.config.mjs
HTML_HTMLHINT_CONFIG_FILE: .htmlhintrc
JAVASCRIPT_PRETTIER_CONFIG_FILE: .prettierrc
JSON_PRETTIER_CONFIG_FILE: .prettierrc
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .markdown-link-check.json
REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yml
REPOSITORY_DEVSKIM_CONFIG_FILE: .devskim.json
REPOSITORY_GRYPE_CONFIG_FILE: .grype.yaml
REPOSITORY_KICS_CONFIG_FILE: kics.yaml
REPOSITORY_SECRETLINT_CONFIG_FILE: .secretlintrc.json
SPELL_CSPELL_CONFIG_FILE: .cspell.json
SPELL_LYCHEE_CONFIG_FILE: lychee.toml
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml

# Disabled linters (use project-specific tools instead)
DISABLE_LINTERS:
    - CSS_STYLELINT # Using project stylelint config
    - TYPESCRIPT_STANDARD # Using ESLint + Prettier
    - JAVASCRIPT_PRETTIER
    - JSON_PRETTIER
    - YAML_PRETTIER
    - TYPESCRIPT_ES # Using ESLint + Prettier
    - JAVASCRIPT_ES # Using ESLint + Prettier
    - JSX_ESLINT # Using ESLint + Prettier
    - CREDENTIALS_SECRETLINT # Using secretlint
    - REPOSITORY_SECRETLINT # Using secretlint
    - TSX_ESLINT # Using ESLint + Prettier
    - TYPESCRIPT_PRETTIER
    - JSON_PRETTIER
    - JSON_JSONLINT
    - JSON_ESLINT_PLUGIN_JSONC

# Error handling for specific linters
JSON_PRETTIER_DISABLE_ERRORS: true
JSON_V8R_DISABLE_ERRORS_IF_LESS_THAN: 2
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
TYPESCRIPT_STANDARD_DISABLE_ERRORS: true

# Excluded directories
EXCLUDED_DIRECTORIES:
    - node_modules
    - dist-electron
    - coverage
    - docs
    - icons
    - assets
    - screenshots
    - libs
    - tests
    - .git
    - .vscode
    - .idea

# Markdown configuration
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: ^.*(CHANGELOG|README|SECURITY)\.md$

# Security and analysis plugins
PLUGINS:
    - https://raw.githubusercontent.com/wesley-dean/mega-linter-plugin-repolinter/refs/heads/main/mega-linter-plugin-repolinter/repolinter.megalinter-descriptor.yml
    - https://raw.githubusercontent.com/andreoliwa/nitpick/v0.35.0/mega-linter-plugin-nitpick/nitpick.megalinter-descriptor.yml
    - https://raw.githubusercontent.com/ssc-services/mega-linter-plugin-salt/main/mega-linter-plugin-salt/salt.megalinter-descriptor.yml
    - https://raw.githubusercontent.com/andreoliwa/nitpick/v0.35.0/mega-linter-plugin-nitpick/nitpick.megalinter-descriptor.yml
    - https://raw.githubusercontent.com/hype8912/check-toml-megalinter-plugin/main/mega-linter-plugin-checktoml/checktoml.megalinter-descriptor.yml

# Reporters configuration
CONFIG_REPORTER: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
JSON_REPORTER: true
JSON_REPORTER_OUTPUT_DETAIL: detailed
MARKDOWN_SUMMARY_REPORTER: true
SARIF_REPORTER: true
TAP_REPORTER: true
TEXT_REPORTER: true
UPDATED_SOURCES_REPORTER: true
CONSOLE_REPORTER: true
CONSOLE_REPORTER_SECTIONS: true
OUTPUT_DETAIL: simple
GITLAB_COMMENT_REPORTER: false
BITBUCKET_COMMENT_REPORTER: false
FILEIO_REPORTER: false
EMAIL_REPORTER: false

# Fixes
APPLY_FIXES: all
