remote_theme: pages-themes/hacker@v0.2.0
title: Uptime-Watcher
description: Uptime-Watcher made by Typpi / Nick2bad4u
url: "https://nick2bad4u.github.io/Uptime-Watcher"
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-feed
    - jekyll-archives
    - jekyll-language-plugin
    - jekyll-algolia
    - jekyll-mentions
    - jekyll-admin
    - jekyll-loading-lazy
