import nick2bad4u from "eslint-config-nick2bad4u";
import betterTailwindcss from "eslint-plugin-better-tailwindcss";
import tailwind from "eslint-plugin-tailwindcss";

import uptimeWatcherPlugin from "./config/linting/plugins/uptime-watcher.mjs";

const unavailableSharedRuleIds = new Set([
    "etc/no-misused-generics",
    "ex/use-error-cause",
    "react-hooks/invariant",
    "react-x/static-components",
    "sonarjs/function-return-type",
    "sonarjs/no-hardcoded-passwords",
    "sql-template/no-unsafe-query",
    "typefest/prefer-ts-extras-string-split",
    "zod/prefer-string-schema-with-trim",
]);

const sanitizeImportedConfig = (config) => {
    if (!config.rules) {
        return config;
    }

    const rules = { ...config.rules };

    for (const ruleId of unavailableSharedRuleIds) {
        delete rules[ruleId];
    }

    // eslint-plugin-unicorn 64 exposes an invalid schema for this rule under
    // ESLint 10. Keep the shared preset usable until upstream fixes it.
    if (rules["unicorn/logical-assignment-operators"]) {
        rules["unicorn/logical-assignment-operators"] = "off";
    }

    return {
        ...config,
        rules,
    };
};

const sharedConfig = nick2bad4u.configs.all.map(sanitizeImportedConfig);

const uptimeWatcherRepoConfigs = (uptimeWatcherPlugin.configs?.repo ?? []).map(
    sanitizeImportedConfig
);

const testFiles = [
    "**/*.{test,spec}.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    "**/test/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    "**/tests/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    "**/strictTests/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    ".storybook/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    "playwright/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    "storybook/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    "**/*.stories.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
];

/** @type {import("eslint").Linter.Config[]} */
const config = [
    {
        ignores: [
            "benchmarks/**/*.ts",
            "config/testing/vitest.zero-coverage.config.ts",
            "config/tools/knip.config.ts",
            "electron-builder.config.ts",
            "eslint.config.mjs",
            "playwright.config.ts",
            "postcss.config.mjs",
            "prettier.config.mjs",
            "stryker.config.mjs",
            "stylelint.config.mjs",
            "tailwind.config.mjs",
            "tests/strictTests/**/*.ts",
            "tests/tooling/**/*.ts",
            "vite*.config.ts",
            "vitest*.config.ts",
        ],
        name: "Uptime Watcher: files checked outside ESLint",
    },
    ...sharedConfig,
    ...uptimeWatcherRepoConfigs,
    {
        files: ["**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}"],
        name: "Uptime Watcher: Tailwind plugin wiring",
        plugins: {
            "better-tailwindcss": betterTailwindcss,
            tailwind,
        },
        rules: {
            // Keep these locally wired, but do not introduce new Tailwind lint
            // failures as part of the shared-config migration.
            "better-tailwindcss/multiline": "off",
            "better-tailwindcss/sort-classes": "off",
            "tailwind/classnames-order": "off",
            "tailwind/enforces-negative-arbitrary-values": "off",
            "tailwind/enforces-shorthand": "off",
            "tailwind/migration-from-tailwind-2": "off",
            "tailwind/no-arbitrary-value": "off",
            "tailwind/no-contradicting-classname": "off",
            "tailwind/no-custom-classname": "off",
        },
    },
    {
        files: ["**/*"],
        name: "Uptime Watcher: dedicated tool lint ownership",
        rules: {
            // These checks run through their own repo scripts with their own
            // config files. Running them inside ESLint duplicates failures and
            // has already caused actionlint worker timeouts on this repo.
            "actionlint/actionlint": "off",
            "remark/remark": "off",
            "stylelint-2/stylelint": "off",
            "tombi/tombi": "off",
            "yamllint/yamllint": "off",
            "css/no-invalid-properties": "off",
            "css/no-invalid-at-rules": "off",
            "css/use-baseline": "off",
            "depend/ban-dependencies": "off",
            "json-schema-validator-2/no-invalid": "off",
            "json/sort-keys": "off",
            "secretlint/secretlint": "off",
        },
    },
    {
        files: ["**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}"],
        name: "Uptime Watcher: repo compatibility overrides",
        rules: {
            // The repo intentionally uses PascalCase component/class files and
            // existing camelCase module names; renaming all files would be a
            // broad source migration rather than lint cleanup.
            "unicorn/filename-case": "off",

            // These ordering rules create large churn and can subtly affect
            // declaration/class field order. Keep import/member linting where it
            // is useful, but do not let mechanical ordering dominate app code.
            "@typescript-eslint/member-ordering": "off",
            "perfectionist/sort-classes": "off",
            "perfectionist/sort-modules": "off",
            "perfectionist/sort-objects": "off",
            "unicorn/consistent-class-member-order": "off",

            // These shared-preset rules are too noisy for this Electron/React
            // app and do not map to current repo conventions.
            "@typescript-eslint/init-declarations": "off",
            "@typescript-eslint/class-methods-use-this": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/no-misused-spread": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-readonly-parameter-types": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/strict-boolean-expressions": "off",
            "canonical/no-use-extend-native": "off",
            "comment-length/limit-single-line-comments": "off",
            "depend/ban-dependencies": "off",
            "func-name-matching": "off",
            complexity: "off",
            "module-interop/no-require-esm": "off",
            "no-duplicate-imports": "off",
            "no-promise-executor-return": "off",
            "no-plusplus": "off",
            "no-underscore-dangle": "off",
            "n/no-process-env": "off",
            "n/no-sync": "off",
            "n/no-unsupported-features/es-syntax": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "json-schema-validator-2/no-invalid": "off",
            "react-x/static-components": "off",
            "@eslint-react/static-components": "off",
            "react-hooks/invariant": "off",
            "sql-template/no-unsafe-query": "off",
            "etc/no-misused-generics": "off",
            "ex/use-error-cause": "off",
            "eslint-plugin/prefer-message-ids": "off",
            "eslint-plugin/require-meta-docs-description": "off",
            "eslint-plugin/require-meta-docs-recommended": "off",
            "eslint-plugin/require-meta-docs-url": "off",
            "eslint-plugin/require-meta-schema": "off",
            "eslint-plugin/require-meta-type": "off",
            "etc-misc/throw-error": "off",
            "import-x/max-dependencies": "off",
            "perfectionist/sort-arrays": "off",
            "perfectionist/sort-imports": "off",
            "perfectionist/sort-interfaces": "off",
            "perfectionist/sort-jsx-props": "off",
            "perfectionist/sort-named-imports": "off",
            "perfectionist/sort-object-types": "off",
            "perfectionist/sort-switch-case": "off",
            "perfectionist/sort-union-types": "off",
            "regexp/require-unicode-regexp": "off",
            "regexp/require-unicode-sets-regexp": "off",
            "tsdoc/syntax": "off",
            "typefest/prefer-type-fest-json-value": "off",
            "typefest/prefer-type-fest-unknown-record": "off",
            "typefest/prefer-ts-extras-array-at": "off",
            "typefest/prefer-ts-extras-array-first": "off",
            "typefest/prefer-ts-extras-array-includes": "off",
            "typefest/prefer-ts-extras-assert-defined": "off",
            "typefest/prefer-ts-extras-is-defined": "off",
            "typefest/prefer-ts-extras-is-finite": "off",
            "typefest/prefer-ts-extras-is-present": "off",
            "typefest/prefer-ts-extras-key-in": "off",
            "typefest/prefer-ts-extras-not": "off",
            "typefest/prefer-ts-extras-object-has-own": "off",
            "typefest/prefer-ts-extras-object-keys": "off",
            "typefest/prefer-ts-extras-safe-cast-to": "off",
            "typefest/prefer-ts-extras-set-has": "off",
            "typefest/prefer-ts-extras-string-split": "off",
            "unicorn/consistent-boolean-name": "off",
            "unicorn/consistent-function-scoping": "off",
            "unicorn/comment-content": "off",
            "unicorn/class-reference-in-static-methods": "off",
            "zod/prefer-string-schema-with-trim": "off",
            "unicorn/max-nested-calls": "off",
            "unicorn/no-break-in-nested-loop": "off",
            "unicorn/no-computed-property-existence-check": "off",
            "unicorn/no-error-property-assignment": "off",
            "unicorn/no-declarations-before-early-exit": "off",
            "unicorn/no-global-object-property-assignment": "off",
            "unicorn/no-non-function-verb-prefix": "off",
            "unicorn/no-this-outside-of-class": "off",
            "unicorn/no-unreadable-new-expression": "off",
            "unicorn/prefer-includes-over-repeated-comparisons": "off",
            "unicorn/prefer-iterator-to-array": "off",
            "unicorn/prefer-global-number-constants": "off",
            "unicorn/prefer-global-this": "off",
            "unicorn/prefer-import-meta-properties": "off",
            "unicorn/prefer-iterator-concat": "off",
            "unicorn/prefer-math-constants": "off",
            "unicorn/prefer-number-coercion": "off",
            "unicorn/prefer-number-is-safe-integer": "off",
            "unicorn/prefer-await": "off",
            "unicorn/prefer-dispose": "off",
            "unicorn/prefer-string-raw": "off",
            "unicorn/prefer-temporal": "off",
            "unicorn/prefer-promise-with-resolvers": "off",
            "unicorn/prefer-uint8array-base64": "off",
            "unicorn/try-complexity": "off",
            "max-classes-per-file": "off",
            "runtime-cleanup/no-floating-abort-controllers": "off",
            "runtime-cleanup/no-floating-timers": "off",
            "runtime-cleanup/no-unmanaged-event-listeners": "off",
            "typedoc/require-exported-doc-comment": "off",
            "typedoc/require-exported-doc-comment-description": "off",
            "typedoc/require-see-tag-link": "off",
            "typedoc/require-throws-tag": "off",
            "tsdoc-require-2/require": "off",
            "@eslint-react/no-forward-ref": "off",
            "unicorn/no-array-callback-reference": "off",
            "unicorn/custom-error-definition": "off",
            "unicorn/no-for-each": "off",
            "unicorn/no-useless-recursion": "off",
            "unicorn/no-negated-comparison": "off",
            "unicorn/no-top-level-side-effects": "off",
            "unicorn/no-unnecessary-global-this": "off",
            "unicorn/no-unreadable-for-of-expression": "off",
            "unicorn/no-unreadable-object-destructuring": "off",
            "unicorn/no-unused-properties": "off",
            "unicorn/no-useless-template-literals": "off",
            "unicorn/prefer-else-if": "off",
            "unicorn/prefer-minimal-ternary": "off",
            "unicorn/prefer-ternary": "off",
            "unicorn/prefer-toggle-attribute": "off",
            "unicorn/prefer-url-href": "off",
        },
    },
    {
        files: [
            "config/linting/plugins/uptime-watcher.mjs",
            "config/linting/plugins/uptime-watcher/**/*.{js,mjs,cjs,ts,tsx,mts,cts}",
        ],
        name: "Uptime Watcher: custom ESLint rule AST compatibility",
        rules: {
            "@eslint-community/eslint-comments/require-description": "off",
            "@typescript-eslint/explicit-member-accessibility": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-require-imports": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-use-before-define": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-enum-comparison": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "canonical/no-re-export": "off",
            "import-x/no-anonymous-default-export": "off",
            "import-x/no-commonjs": "off",
            "import-x/unambiguous": "off",
            "no-barrel-files/no-barrel-files": "off",
            "max-lines-per-function": "off",
            "security/detect-non-literal-fs-filename": "off",
            "unicorn/no-top-level-side-effects": "off",
            "unicorn/no-top-level-assignment-in-function": "off",
            "unicorn/prefer-short-arrow-method": "off",
        },
    },
    {
        files: [
            ".storybook/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
            "storybook/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
        ],
        name: "Uptime Watcher: Storybook config files",
        rules: {
            "import-x/extensions": "off",
            "storybook/csf-component": "off",
            "storybook/meta-satisfies-type": "off",
            "storybook/story-exports": "off",
        },
    },
    {
        files: ["docs/docusaurus/src/**/*.{js,jsx,ts,tsx}"],
        name: "Uptime Watcher: Docusaurus app compatibility",
        rules: {
            "@typescript-eslint/no-deprecated": "off",
            "canonical/filename-no-index": "off",
            "docusaurus-2/no-page-css-module-imports-in-components": "off",
            "no-console": "off",
            "unicorn/no-incorrect-template-string-interpolation": "off",
            "unicorn/prefer-observer-apis": "off",
        },
    },
    {
        files: [
            "config/linting/remark/**/*.mjs",
            "docs/docusaurus/typedoc-plugins/**/*.mjs",
        ],
        name: "Uptime Watcher: local documentation tooling",
        rules: {
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "import-x/no-extraneous-dependencies": "off",
            "n/no-extraneous-import": "off",
            "prefer-named-capture-group": "off",
            "regexp/no-super-linear-backtracking": "off",
            "regexp/no-super-linear-move": "off",
            "regexp/no-unused-capturing-group": "off",
            "regexp/prefer-named-capture-group": "off",
            "security/detect-non-literal-fs-filename": "off",
            "security/detect-non-literal-regexp": "off",
            "security/detect-unsafe-regex": "off",
            "unicorn/default-export-style": "off",
            "unicorn/better-dom-traversing": "off",
        },
    },
    {
        files: [
            "shared/utils/errorHandling.ts",
            "shared/utils/objectSafety.ts",
        ],
        name: "Uptime Watcher: shared fallback console reporting",
        rules: {
            "no-console": "off",
        },
    },
    {
        files: ["electron/constants.ts"],
        name: "Uptime Watcher: shared constant aliases",
        rules: {
            "canonical/no-re-export": "off",
        },
    },
    {
        files: ["src/stores/settings/useSettingsStore.ts"],
        name: "Uptime Watcher: Zustand persist store initializer",
        rules: {
            "@typescript-eslint/strict-void-return": "off",
        },
    },
    {
        files: testFiles,
        name: "Uptime Watcher: existing test-suite compatibility",
        rules: {
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/dot-notation": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-floating-promises": "off",
            "@typescript-eslint/explicit-member-accessibility": "off",
            "@typescript-eslint/only-throw-error": "off",
            "@typescript-eslint/consistent-type-imports": "off",
            "@typescript-eslint/await-thenable": "off",
            "@typescript-eslint/no-base-to-string": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-loop-func": "off",
            "@typescript-eslint/no-misused-promises": "off",
            "@typescript-eslint/no-restricted-imports": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unnecessary-type-assertion": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-function-type": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/no-non-null-assertion": "off",
            "@typescript-eslint/no-non-null-asserted-optional-chain": "off",
            "@typescript-eslint/no-redundant-type-constituents": "off",
            "@typescript-eslint/no-restricted-types": "off",
            "@typescript-eslint/no-shadow": "off",
            "@typescript-eslint/no-unused-vars": "off",
            "@typescript-eslint/explicit-module-boundary-types": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/restrict-plus-operands": "off",
            "@typescript-eslint/strict-boolean-expressions": "off",
            "@typescript-eslint/strict-void-return": "off",
            "@typescript-eslint/switch-exhaustiveness-check": "off",
            "@typescript-eslint/unbound-method": "off",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
            "@eslint-community/eslint-comments/require-description": "off",
            "@eslint-react/globals": "off",
            "test-signal/no-conditional-assertions": "off",
            "test-signal/no-constant-assertions": "off",
            "test-signal/no-duplicate-assertions": "off",
            "test-signal/no-fixed-delay-tests": "off",
            "test-signal/no-identical-expected-actual": "off",
            "test-signal/no-mock-call-only-tests": "off",
            "test-signal/no-try-catch-assertions": "off",
            "test-signal/require-error-message-assertions": "off",
            "test-signal/no-weak-existence-assertions": "off",
            "test-signal/no-weak-asymmetric-assertions": "off",
            "test-signal/no-weak-truthy-assertions": "off",
            "test-signal/no-assertions-in-hooks": "off",
            "test-signal/no-broad-object-key-count-assertions": "off",
            "test-signal/no-empty-async-tests": "off",
            "test-signal/no-tautological-length-assertions": "off",
            "test-signal/require-negative-path": "off",
            "test-signal/require-assertions": "off",
            "testing-library/no-node-access": "off",
            "testing-library/no-debugging-utils": "off",
            "testing-library/no-test-id-queries": "off",
            "testing-library/prefer-implicit-assert": "off",
            "testing-library/prefer-explicit-assert": "off",
            "testing-library/prefer-user-event": "off",
            "@eslint-react/dom-no-missing-button-type": "off",
            "@eslint-react/jsx-no-children-prop": "off",
            "@eslint-react/no-implicit-children": "off",
            "etc-misc/no-vulnerable": "off",
            "etc-misc/no-unnecessary-template-literal": "off",
            "etc-misc/no-unnecessary-initialization": "off",
            "etc-misc/throw-error": "off",
            "import-x/no-unassigned-import": "off",
            "import-x/no-unresolved": "off",
            "array-callback-return": "off",
            "default-case": "off",
            "func-names": "off",
            "listeners/no-inline-function-event-listener": "off",
            "listeners/matching-remove-event-listener": "off",
            "listeners/no-missing-remove-event-listener": "off",
            "max-lines-per-function": "off",
            "max-depth": "off",
            "n/callback-return": "off",
            "n/global-require": "off",
            "n/no-top-level-await": "off",
            "n/no-callback-literal": "off",
            "n/prefer-global/crypto": "off",
            "no-await-in-loop": "off",
            "no-console": "off",
            "no-new": "off",
            "no-useless-escape": "off",
            "new-cap": "off",
            "nitpick/no-redundant-vars": "off",
            "no-unsanitized/method": "off",
            "promise/param-names": "off",
            "promise/always-return": "off",
            "promise/prefer-await-to-then": "off",
            "prefer-named-capture-group": "off",
            "regexp/hexadecimal-escape": "off",
            "regexp/letter-case": "off",
            "regexp/no-control-character": "off",
            "regexp/no-dupe-disjunctions": "off",
            "regexp/no-empty-group": "off",
            "regexp/no-super-linear-backtracking": "off",
            "regexp/no-super-linear-move": "off",
            "regexp/no-unused-capturing-group": "off",
            "regexp/prefer-lookaround": "off",
            "regexp/prefer-regexp-exec": "off",
            "regexp/prefer-named-capture-group": "off",
            "regexp/strict": "off",
            "sdl/no-insecure-random": "off",
            "sdl/no-insecure-url": "off",
            "sdl/no-child-process-exec": "off",
            "sdl/no-inner-html": "off",
            "sdl/no-nonnull-assertion-on-security-input": "off",
            "security/detect-non-literal-fs-filename": "off",
            "security/detect-non-literal-regexp": "off",
            "security/detect-unsafe-regex": "off",
            "math/prefer-math-sum-precise": "off",
            "typefest/prefer-ts-extras-assert-defined": "off",
            "typefest/prefer-ts-extras-is-finite": "off",
            "typefest/prefer-ts-extras-is-present": "off",
            "typefest/prefer-ts-extras-is-present-filter": "off",
            "typefest/prefer-ts-extras-key-in": "off",
            "typefest/prefer-ts-extras-not": "off",
            "typefest/prefer-ts-extras-object-has-own": "off",
            "typefest/prefer-ts-extras-object-map-values": "off",
            "typefest/prefer-ts-extras-object-assign": "off",
            "typefest/prefer-ts-extras-assert-present": "off",
            "typefest/prefer-ts-extras-is-empty": "off",
            "typefest/prefer-ts-extras-is-infinite": "off",
            "typefest/prefer-ts-extras-set-has": "off",
            "typefest/prefer-type-fest-except": "off",
            "typefest/prefer-type-fest-promisable": "off",
            "typefest/prefer-type-fest-set-return-type": "off",
            "runtime-cleanup/no-floating-timers": "off",
            "runtime-cleanup/no-unmanaged-event-listeners": "off",
            "canonical/prefer-use-mount": "off",
            "@eslint-react/exhaustive-deps": "off",
            "@eslint-react/no-leaked-conditional-rendering": "off",
            "@eslint-react/no-unnecessary-use-prefix": "off",
            "@eslint-react/no-unused-props": "off",
            "testing-library/consistent-data-testid": "off",
            "require-atomic-updates": "off",
            "unicorn/no-array-from-fill": "off",
            "unicorn/no-array-front-mutation": "off",
            "unicorn/no-array-reduce": "off",
            "unicorn/no-array-sort": "off",
            "unicorn/no-await-expression-member": "off",
            "unicorn/no-duplicate-if-branches": "off",
            "unicorn/no-empty-file": "off",
            "unicorn/no-incorrect-template-string-interpolation": "off",
            "unicorn/no-nonstandard-builtin-properties": "off",
            "unicorn/no-return-array-push": "off",
            "unicorn/no-unsafe-dom-html": "off",
            "unicorn/no-unsafe-string-replacement": "off",
            "unicorn/no-unnecessary-splice": "off",
            "unicorn/no-useless-delete-check": "off",
            "unicorn/operator-assignment": "off",
            "unicorn/prefer-abort-signal-timeout": "off",
            "unicorn/prefer-array-last-methods": "off",
            "unicorn/prefer-boolean-return": "off",
            "unicorn/prefer-dom-node-html-methods": "off",
            "unicorn/prefer-hoisting-branch-code": "off",
            "unicorn/prefer-module": "off",
            "unicorn/prefer-logical-operator-over-ternary": "off",
            "unicorn/prefer-object-define-properties": "off",
            "unicorn/prefer-scoped-selector": "off",
            "unicorn/prefer-set-methods": "off",
            "unicorn/prefer-unicode-code-point-escapes": "off",
            "unicorn/require-array-sort-compare": "off",
            "unicorn/no-top-level-assignment-in-function": "off",
            "unicorn/no-unused-properties": "off",
            "uptime-watcher/no-regexp-v-flag": "off",
            "playwright/max-expects": "off",
            "playwright/no-conditional-in-test": "off",
            "playwright/no-hooks": "off",
            "playwright/no-nth-methods": "off",
            "playwright/require-soft-assertions": "off",
            "playwright/require-hook": "off",
            "vitest/consistent-test-it": "off",
            "vitest/prefer-hooks-in-order": "off",
            "vitest/unbound-method": "off",
            "vitest/no-conditional-tests": "off",
            "vitest/no-duplicate-hooks": "off",
            "vitest/max-expects": "off",
            "vitest/no-conditional-expect": "off",
            "vitest/no-conditional-in-test": "off",
            "vitest/no-hooks": "off",
            "vitest/no-standalone-expect": "off",
            "vitest/no-test-return-statement": "off",
            "vitest/padding-around-all": "off",
            "vitest/padding-around-expect-groups": "off",
            "vitest/prefer-called-with": "off",
            "vitest/prefer-describe-function-title": "off",
            "vitest/prefer-each": "off",
            "vitest/prefer-expect-assertions": "off",
            "vitest/prefer-expect-type-of": "off",
            "vitest/prefer-import-in-mock": "off",
            "vitest/prefer-lowercase-title": "off",
            "vitest/prefer-strict-boolean-matchers": "off",
            "vitest/prefer-strict-equal": "off",
            "vitest/require-to-throw-message": "off",
            "vitest/require-top-level-describe": "off",
            "vitest/require-mock-type-parameters": "off",
        },
    },
    {
        files: ["vitest.shims.d.ts"],
        name: "Uptime Watcher: intentionally empty Vitest shim",
        rules: {
            "unicorn/no-empty-file": "off",
        },
    },
];

export default config;
