#############################  Display  #############################

# Verbose program output
# Accepts log level: "error", "warn", "info", "debug", "trace"
verbose = "info"

# Don't show interactive progress bar while checking links.
no_progress = false

# # Path to summary output file.
# output = ".config.dummy.report.md"

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "30d"

#############################  Runtime  #############################

# Number of threads to utilize.
# Defaults to number of cores available to the system if omitted.
threads = 2

# Maximum number of allowed redirects.
max_redirects = 15

# Maximum number of allowed retries before a link is declared dead.
max_retries = 3

# Maximum number of concurrent link checks.
max_concurrency = 10

#############################  Requests  ############################

# User agent to send with each request.
user_agent = "curl/7.83. 1"

# Website timeout from connect to response finished.
timeout = 20

# Minimum wait time in seconds between retries of failed requests.
retry_wait_time = 3

# Comma-separated list of accepted status codes for valid links.
# Supported values are:
#
# accept = ["200..=204", "429"]
# accept = "200..=204, 429"
# accept = ["200", "429"]
# accept = "200, 429"
accept = ["200", "429"]

# Proceed for server connections considered insecure (invalid TLS).
insecure = true

# Only test links with the given schemes (e.g. https).
# Omit to check links with any other scheme.
# At the moment, we support http, https, file, and mailto.
scheme = ["https", "http", "mailto"]

# When links are available using HTTPS, treat HTTP links as errors.
require_https = false

# Request method
method = "get"

# # Custom request headers
# headers = []

# # Remap URI matching pattern to different URI.
# remap = ["https://example.com http://example.invalid"]

# Base URL or website root directory to check relative URLs.
base = "https://github.com/Nick2bad4u/FitFileViewer"

# # HTTP basic auth support. This will be the username and password passed to the
# # authorization HTTP header. See
# # <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization>
# basic_auth = ["example.com user:pwd"]

#############################  Exclusions  ##########################

# Skip missing input files (default is to error if they don't exist).
skip_missing = false

# Check links inside `<code>` and `<pre>` blocks as well as Markdown code
# blocks.
include_verbatim = false

# Ignore case of paths when matching glob patterns.
glob_ignore_case = false

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
    '^https://www\.linkedin\.com',
    '^https://web\.archive\.org/web/',
    '^https://github\.com',
    '^https://raw\.githubusercontent\.com',
    '^https://gist\.github\.com',
    '^https://api\.github\.com',
    '^https://docs\.github\.com',
    '^https://help\.github\.com',
    '^https://github\.io',
    '^mailto:20943337\+Nick2bad4u@users\.noreply\.github\.com',
    '^mailto:nick2bad4u@users\.noreply\.github\.com',
    '^mailto:support@github\.com',
    '^mailto:bot@stepsecurity\.io',
    '^mailto:github-actions@github\.com',
    '^https://nick2bad4u/',
    '^https://views\.igorkowalczyk\.dev/api/badge/fitfileviewer\?style=flat',
    '^https://registry\.npmjs\.org',
    '^https://www\.patreon\.com/feross',
]

# Exclude these filesystem paths from getting checked.
exclude_path = [
    "github/workflows",
    "electron-app/libs",
    "electron-app/node_modules",
    "node_modules",
    "package.json",
    "package-lock.json",
    "yarn.lock"
]

# # URLs to check (supports regex). Has preference over all excludes.
# include = ['gist\.github\.com.*']

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = true

# Exclude private IP address ranges from checking.
exclude_private = true

# Exclude link-local IP address range from checking.
exclude_link_local = true

# Exclude loopback IP address range and localhost from checking.
exclude_loopback = true

# Check mail addresses
include_mail = true