/**
 * Repository-specific configuration for Knip dependency analysis.
 *
 * @packageDocumentation
 */
import type { KnipConfig } from "knip";

/**
 * Knip configuration that scopes entry points and dependency heuristics to the
 * Uptime Watcher monorepo layout.
 */
const knipConfig: KnipConfig = {
    $schema: "https://unpkg.com/knip@5/schema.json",
    entry: [
        ".storybook/main.ts",
        "electron/main.ts",
        "electron/preload.ts",
        "shared/types.ts",
        "src/App.tsx",
        "src/main.tsx",
        "storybook/viteSharedConfig.ts",
        "vite.config.ts",
        "vitest.config.ts",
        "vitest.electron.config.ts",
        "vitest.shared.config.ts",
        "vitest.storybook.config.ts",
        "vitest.stryker.config.ts",
    ],
    ignore: [
        "**/*.bench.ts",
        "**/*.spec.ts",
        "**/*.test.ts",
        "**/test/**",
        "**/tests/**",
        "benchmarks/**",
        "docs/**",
        "scripts/**",
        "shared/types/monitorTypes.ts",
        "shared/types/themeConfig.ts",
    ],
    ignoreBinaries: [
        "actionlint",
        "deploy",
        "detect-secrets",
        "docusaurus",
        "eslint-find-rules",
        "gh",
        "git-cz",
        "grype",
        "hint",
        "jq",
        "markdownlint",
        "ncu",
        "npm-check",
        "npm-check-updates",
        "open-cli",
        "powershell",
        "repomix",
        "resolve-audit",
        "rimraf",
        "scorecard-check",
        "serve",
        "sloc",
        "ts-node",
        "tsg",
        "typesync",
        "winget",
        "yamllint",
        "config/tools/knip.config.ts",
    ],
    ignoreDependencies: [
        ".*eslint-formatter-.*",
        ".*prettier.*",
        "@commitlint.*",
        "@cspell.*",
        "@csstools/stylelint-formatter-github",
        "@dword-design/eslint-plugin-import-alias",
        "@electron/notarize",
        "@eslint.*",
        "@executeautomation/database-server",
        "@jscpd.*",
        "@microsoft/tsdoc-config",
        "@modelcontextprotocol/server-sequential-thinking",
        "@putout.*",
        "@secretlint.*",
        "@snyk/protect",
        "@storybook.*",
        "@stylelint.*",
        "@stylistic/eslint-plugin",
        "@tailwindcss/forms",
        "@tailwindcss/typography",
        "@types.*",
        "@vitest.*",
        "async",
        "babel-plugin-react-compiler",
        "chartjs-adapter-date-fns",
        "chartjs-plugin-zoom",
        "cli-table3",
        "cssnano",
        "cssnano-preset-advanced",
        "docusaurus-plugin-typedoc",
        "electron.*",
        "eslint.*",
        "fast-deep-equal",
        "force",
        "fs-extra",
        "globals-vitest",
        "gray-matter",
        "istanbul.*",
        "lcov-result-merger",
        "madge",
        "markdown-to-jsx",
        "markdownlint",
        "node-abi",
        "nyc",
        "pkg-types",
        "postcss.*",
        "putout",
        "react-chartjs-2",
        // False-positive: the project imports icons from deep entrypoints
        // (e.g. `react-icons/fi`). Knip does not currently attribute those
        // imports back to the top-level `react-icons` dependency.
        "react-icons",
        "react-refresh",
        "remark.*",
        "secretlint",
        "stylelint.*",
        "tailwind.*",
        "tidy-markdown",
        "ts.*",
        "tw-animate-css",
        "type.*",
        "unified",
        "vite.*",
        "ws",
        "zod-fast-check",
        // False-positive: used by the Electron Google Drive provider, but Knip
        // does not currently detect it as a referenced dependency.
        "googleapis",
    ],
    ignoreExportsUsedInFile: {
        interface: true,
        type: true,
    },
    ignoreUnresolved: [],
    includeEntryExports: true,
    project: [
        "!**/*.d.ts",
        "!**/coverage/**",
        "!**/dist/**",
        "!**/node_modules/**",
        "electron/**/*.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
        "shared/**/*.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
        "src/**/*.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
    ],
    rules: {
        binaries: "error",
        classMembers: "warn",
        dependencies: "error",
        devDependencies: "error",
        duplicates: "error",
        enumMembers: "warn",
        exports: "warn",
        files: "error",
        nsExports: "warn",
        nsTypes: "warn",
        optionalPeerDependencies: "error",
        types: "warn",
        unlisted: "error",
        unresolved: "error",
    },
    workspaces: {
        ".": {
            entry: [],
            project: [],
        },
        electron: {
            entry: ["electron/main.ts", "electron/preload.ts"],
            project: [
                "!electron/**/*.spec.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
                "!electron/**/*.test.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
                "electron/**/*.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
            ],
        },
        shared: {
            entry: ["shared/index.ts"],
            project: [
                "!shared/**/*.spec.ts",
                "!shared/**/*.test.ts",
                "shared/**/*.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
            ],
        },
        src: {
            entry: ["src/main.tsx"],
            project: [
                "!src/**/*.spec.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
                "!src/**/*.test.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
                "src/**/*.{js,ts,tsx,jsx,mts,cjs,cts,mjs}",
            ],
        },
    },
};

export default knipConfig;
