// THIS FILE IS AUTO-GENERATED BY scripts/generate-ipc-artifacts.mts. DO NOT EDIT.

/**
 * Shared type definition for the preload events bridge.
 *
 * @remarks
 * Ensures the Electron preload layer and renderer agree on the shape of the
 * event subscription API exposed through `window.electronAPI.events`.
 */
import type {
    RendererEventChannel,
    RendererEventPayloadMap,
} from "@shared/ipc/rendererEvents";

type CacheInvalidatedPayload = RendererEventPayloadMap["cache:invalidated"];
type HistoryLimitUpdatedPayload =
    RendererEventPayloadMap["settings:history-limit-updated"];
type MonitorCheckCompletedPayload =
    RendererEventPayloadMap["monitor:check-completed"];
type MonitoringStartedPayload = RendererEventPayloadMap["monitoring:started"];
type MonitoringStoppedPayload = RendererEventPayloadMap["monitoring:stopped"];
type MonitorStatusChangedPayload =
    RendererEventPayloadMap["monitor:status-changed"];
type StateSyncEventPayload = RendererEventPayloadMap["state-sync-event"];
type UpdateStatusPayload = RendererEventPayloadMap["update-status"];

/**
 * Contract for the preload events bridge exposed to the renderer.
 *
 * @public
 */
export interface EventsDomainBridge {
    /**
     * Subscribe to events emitted on the `cache:invalidated` channel.
     *
     * @param callback - Invoked with payloads emitted on the
     *   `cache:invalidated` channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onCacheInvalidated: (
        callback: (data: CacheInvalidatedPayload) => void
    ) => () => void;

    /**
     * Subscribe to events emitted on the `settings:history-limit-updated`
     * channel.
     *
     * @param callback - Invoked with payloads emitted on the
     *   `settings:history-limit-updated` channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onHistoryLimitUpdated: (
        callback: (data: HistoryLimitUpdatedPayload) => void
    ) => () => void;

    /**
     * Subscribe to events emitted on the `monitor:check-completed` channel.
     *
     * @param callback - Invoked with payloads emitted on the
     *   `monitor:check-completed` channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onMonitorCheckCompleted: (
        callback: (data: MonitorCheckCompletedPayload) => void
    ) => () => void;

    /**
     * Subscribe to events emitted on the `monitoring:started` channel.
     *
     * @param callback - Invoked with payloads emitted on the
     *   `monitoring:started` channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onMonitoringStarted: (
        callback: (data: MonitoringStartedPayload) => void
    ) => () => void;

    /**
     * Subscribe to events emitted on the `monitoring:stopped` channel.
     *
     * @param callback - Invoked with payloads emitted on the
     *   `monitoring:stopped` channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onMonitoringStopped: (
        callback: (data: MonitoringStoppedPayload) => void
    ) => () => void;

    /**
     * Subscribe to events emitted on the `monitor:status-changed` channel.
     *
     * @param callback - Invoked with payloads emitted on the
     *   `monitor:status-changed` channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onMonitorStatusChanged: (
        callback: (data: MonitorStatusChangedPayload) => void
    ) => () => void;

    /**
     * Subscribe to events emitted on the `state-sync-event` channel.
     *
     * @param callback - Invoked with payloads emitted on the `state-sync-event`
     *   channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onStateSyncEvent: (
        callback: (data: StateSyncEventPayload) => void
    ) => () => void;

    /**
     * Subscribe to events emitted on the `update-status` channel.
     *
     * @param callback - Invoked with payloads emitted on the `update-status`
     *   channel.
     *
     * @returns Cleanup function that removes the registered listener.
     */
    readonly onUpdateStatus: (
        callback: (data: UpdateStatusPayload) => void
    ) => () => void;

    /**
     * Remove registered renderer event listeners.
     *
     * @param channel - Optional channel to clear. Omitting it clears every
     *   renderer event listener.
     */
    readonly removeAllListeners: (channel?: RendererEventChannel) => void;
}
