/**
 * Theme Switch UI Tests
 *
 * @remarks
 * Generated by Playwright codegen and improved for lint compliance
 *
 * @file Playwright test for theme switching functionality
 */

import { test, expect } from "@playwright/test";
import { ensureCleanState } from "../utils/modal-cleanup";
import { launchElectronApp } from "../fixtures/electron-helpers";

test.describe("theme switch UI", () => {
    test("should toggle between light and dark themes", async () => {
        const electronApp = await launchElectronApp();

        const page = await electronApp.firstWindow();
        await page.waitForLoadState("domcontentloaded");
        await ensureCleanState(page);

        // Wait for the React app to fully load
        await expect(page.getByTestId("app-root")).toBeVisible({
            timeout: 15000,
        });

        // Test initial state (light theme shows moon icon)
        await expect(page.getByLabel("Toggle theme")).toContainText("🌙");

        // Toggle to dark theme (shows sun icon)
        await page.getByRole("button", { name: "Toggle theme" }).click();
        await expect(page.getByLabel("Toggle theme")).toContainText("☀️");

        // Toggle back to light theme (shows moon icon)
        await page.getByRole("button", { name: "Toggle theme" }).click();
        await expect(page.getByLabel("Toggle theme")).toContainText("🌙");

        // Verify app container and main content is visible
        const appContainer = page.getByTestId("app-container");
        await expect(appContainer).toBeVisible();

        // Verify main UI elements using aria snapshot
        await expect(appContainer).toMatchAriaSnapshot(`
        - banner:
          - text: 📊 Uptime Watcher 0 Up 0 Down 0 Pending 0 Paused
          - button "Add new site": ➕
          - button "Toggle theme": 🌙
          - button "Settings": ⚙️
        - main: Monitored Sites (0) 🌐 No sites are being monitoredAdd your first website to start monitoring its uptime.
        `);

        await electronApp.close();
    });
});
