/**
 * Theme Switch UI Tests
 *
 * @remarks
 * Generated by Playwright codegen and improved for lint compliance
 *
 * @file Playwright test for theme switching functionality
 */

import { test, expect } from "@playwright/test";

test.describe("theme switch UI", () => {
    test("should toggle between light and dark themes", async ({ page }) => {
        // Test initial state (light theme)
        await expect(page.getByLabel("Toggle theme")).toContainText("☀️");

        // Toggle to dark theme
        await page.getByRole("button", { name: "Toggle theme" }).click();
        await expect(page.getByLabel("Toggle theme")).toContainText("🌙");

        // Toggle back to light theme
        await page.getByRole("button", { name: "Toggle theme" }).click();
        await expect(page.getByLabel("Toggle theme")).toContainText("☀️");

        // Verify app container and main content is visible
        const appContainer = page.getByTestId("app-container");
        await expect(appContainer).toBeVisible();

        // Verify main UI elements using aria snapshot
        await expect(appContainer).toMatchAriaSnapshot(`
        - text: /📊 Uptime Watcher 0% Health 0 Up 0 Down 0 Pending \\d+ Paused \\d+ Total/
        - button "Add new site"
        - button "Toggle theme"
        - button "Settings"
        `);
    });
});
