baseurl: "/Uptime-Watcher"

# Collections for better organization
collections:
    api:
        output: true
        permalink: /:collection/:name/
    components:
        output: true
        permalink: /:collection/:name/

    guides:
        output: true
        permalink: /:collection/:name/
defaults:
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "default"
    - scope:
          path: ""
          type: "TSDoc"
      values:
          layout: "default"

description: >-
    Comprehensive documentation for Uptime Watcher - A cross-platform desktop
    application for monitoring website uptime and server availability
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge

# Jekyll settings
markdown: kramdown
# Navigation
navigation:
    - title: "Home"
      url: /
    - title: "TSDoc"
      url: /TSDoc/
    - title: "GitHub"
      url: https://github.com/Nick2bad4u/Uptime-Watcher

# Pagination settings (for jekyll-paginate)
paginate: 10
paginate_path: "/page:num/"
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-relative-links
    - jekyll-github-metadata
    - jekyll-mentions
    - jekyll-gist
    - jekyll-avatar
    - jekyll-default-layout
    - jekyll-optional-front-matter
    - jekyll-titles-from-headings
    - jekyll-include-cache
    - jekyll-redirect-from
    - jemoji

# Plugin settings
relative_links:
    collections: true
    enabled: true
theme: jekyll-theme-hacker
title: Uptime Watcher Documentation
url: "https://nick2bad4u.github.io"
