# GitHub Action to build Flatpak using flatpak-builder
# This workflow builds your Electron app as a Flatpak using flatpak-builder directly.

name: Build Flatpak

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Build and Release Electron App"]
        types:
            - completed

concurrency:
    group: flatpak-build-${{ github.ref }}
    cancel-in-progress: false

jobs:
    build-flatpak:
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
              with:
                  egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - name: Cache node modules (non-Windows)
              id: cache_node_modules_non_windows
              if: runner.os != 'Windows'
              uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
                  enableCrossOsArchive: true
              continue-on-error: true

            - name: Install Flatpak and flatpak-builder
              run: |
                  sudo apt-get update
                  sudo apt-get install -y flatpak flatpak-builder elfutils libarchive-tools
                  # IMPORTANT: Install EVERYTHING system-wide (no --user) so flatpak-builder sandbox can see extensions.
                  # --user installs are NOT visible inside the build sandbox -> caused missing org.freedesktop.Sdk.Extension.node24.
                  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                  flatpak install -y --noninteractive flathub \
                    org.freedesktop.Platform//24.08 \
                    org.freedesktop.Sdk//24.08 \
                    org.electronjs.Electron2.BaseApp//24.08 \
                    org.freedesktop.Sdk.Extension.node24//24.08
                  flatpak update -y
              continue-on-error: true

            - name: Verify Flatpak components
              run: |
                  echo "Verifying required Flatpak components are available (system scope)";
                  flatpak info org.freedesktop.Platform//24.08 || exit 1
                  flatpak info org.freedesktop.Sdk//24.08 || exit 1
                  flatpak info org.electronjs.Electron2.BaseApp//24.08 || exit 1
                  flatpak info org.freedesktop.Sdk.Extension.node24//24.08 || (echo "node24 extension missing" && exit 1)
              continue-on-error: true

        # Removed duplicate SDK extension install step (handled above system-wide)

            - name: Set up Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: "latest"

            - name: Install dependencies
              run: |
                  cd .
                  npm install --force

            - name: Build application
              run: |
                  npm run build

            - name: Smoke-check build artifacts
              run: |
                  echo "Checking for dist-electron/main.js and sqlite wasm..."
                  if [ ! -f "dist-electron/main.js" ]; then
                    echo "Error: dist-electron/main.js not found"
                    ls -la dist-electron || true
                    exit 1
                  fi
                  if [ ! -f "dist-electron/node-sqlite3-wasm.wasm" ] && [ ! -f "dist-electron/node-sqlite3-wasm.wasm" ]; then
                    # check typical wasm locations
                    echo "Warning: node-sqlite3-wasm.wasm not found in dist-electron"
                    ls -la dist-electron || true
                    exit 1
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Flatpak
              run: |
                  cd .
                  ls -l
                  # Build into a proper flatpak repo directory
                  flatpak-builder --repo=flatpak-repo --force-clean build-dir flatpak-build.yml
                  ls -l
                  ls -l dist-electron || true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CI: true
                  DEBUG: "@malept/flatpak-bundler"

            - name: Create FlatPak bundle
              run: |
                  cd .
                  ls -l
                  ls -l flatpak-repo || true
                  # Use the correct app ID from the manifest and the flatpak-repo produced by flatpak-builder
                  flatpak build-bundle flatpak-repo Uptime-Watcher.flatpak io.github.uptimewatcher
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CI: true
                  DEBUG: "@malept/flatpak-bundler"

            # Optionally, upload the FlatPak bundle as an artifact
            - name: Upload FlatPak bundle
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                  name: flatpak-bundle
                  path: ./Uptime-Watcher.flatpak

            - name: Zip Flatpak bundle
              run: |
                  cd .
                  ls -l
                  zip Uptime-Watcher.flatpak.zip Uptime-Watcher.flatpak

            - name: Get latest release tag
              id: get_release
              uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
              with:
                  script: |
                      const releases = await github.rest.repos.listReleases({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                      });
                      if (releases.data.length === 0) {
                        throw new Error('No releases found');
                      }
                      return releases.data[0].tag_name;
                  result-encoding: string

            - name: Rename Flatpak and zip with version
              run: |
                  cd .
                  mv Uptime-Watcher.flatpak Uptime-Watcher-${{ steps.get_release.outputs.result }}.flatpak
                  mv Uptime-Watcher.flatpak.zip Uptime-Watcher-${{ steps.get_release.outputs.result }}.flatpak.zip

            - name: Upload .flatpak and .zip to latest release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_TAG: ${{ steps.get_release.outputs.result }}
              run: |
                  gh release upload "$RELEASE_TAG" "./Uptime-Watcher-${RELEASE_TAG}.flatpak" "./Uptime-Watcher-${RELEASE_TAG}.flatpak.zip" --clobber
