# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Mark Stale Issues And Pull Requests
run-name: Mark stale issues and pull requests

"on":
    schedule:
        - cron: "38 7 * * *"
    pull_request_target:
        branches: [main]
        types:
            - opened
            - reopened
            - synchronize
    issues:
        types:
            - opened
            - reopened
            - edited
    workflow_dispatch:

concurrency:
    group: stale-${{ github.ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    stale:
        name: Mark stale issues and pull requests
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            issues: write
            pull-requests: write
        concurrency:
            group: stale-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
              with:
                  egress-policy: audit

            - name: Mark stale issues and pull requests
              uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: "Stale issue"
                  stale-pr-message: "Stale pull request"
                  stale-issue-label: "no-issue-activity"
                  stale-pr-label: "no-pr-activity"
